"""
Postmortem Writer Agent

Responsibilities:
- Generate comprehensive incident postmortem
- Document timeline, root cause, and fix
- Suggest preventive measures
- Output in Markdown format
"""

from datetime import datetime, timezone
from app.graph.state import IncidentState, add_timeline_entry


POSTMORTEM_TEMPLATE = """# Incident Postmortem

## Incident Summary

**Incident ID:** {incident_id}  
**Incident Type:** {incident_type}  
**Severity:** {severity}  
**Status:** {status}  
**Duration:** {duration}

**Affected Resources:**
{affected_resources}

## Timeline

{timeline}

## Root Cause Analysis

{root_cause}

### Hypotheses Investigated

{hypotheses}

### Diagnostic Evidence

{diagnostics}

## Resolution

### Primary Remediation

**Action:** {remediation_action}  
**Risk Level:** {risk_level}  
**Requires PR:** {requires_pr}  

**Description:** {remediation_description}

**Estimated Impact:** {estimated_impact}

{command}

### Alternative Approaches Considered

{alternatives}

## Preventive Measures

{preventive_measures}

## Lessons Learned

{lessons_learned}

---

*Generated by SRE Autonomous Agent*  
*Report generated at: {generated_at}*
"""


def postmortem_agent(state: IncidentState) -> IncidentState:
    """
    Generate incident postmortem documentation
    """
    
    # Calculate duration
    start = datetime.fromisoformat(state["started_at"])
    end = datetime.now(timezone.utc)
    duration = str(end - start).split('.')[0]  # Remove microseconds
    
    # Format timeline
    timeline_md = "\n".join([
        f"- **{entry['timestamp']}** [{entry['agent']}] {entry['action']}: {entry['details']}"
        for entry in state["timeline"]
    ])
    
    # Format hypotheses
    hypotheses_md = "\n".join([
        f"{i+1}. **{h['description']}** (confidence: {h['confidence']}, category: {h['category']})"
        for i, h in enumerate(state["hypotheses"])
    ])
    
    # Format diagnostics
    diagnostics_md = "\n".join([
        f"- **{d['source']}** at {d['timestamp']}: {d['data']}"
        for d in state["diagnostics"]
    ])
    
    # Format affected resources
    resources_md = "\n".join([
        f"- **{k}:** {v}"
        for k, v in state["affected_resources"].items()
    ])
    
    # Format alternatives
    alternatives_md = "\n".join([
        f"{i+1}. **{alt['description']}** (Risk: {alt['risk_level']})"
        for i, alt in enumerate(state["alternative_plans"])
    ]) if state["alternative_plans"] else "None"
    
    # Generate preventive measures (simplified - could use LLM)
    preventive_measures = generate_preventive_measures(state)
    lessons_learned = generate_lessons_learned(state)
    
    # Remediation command formatting
    command_md = ""
    if state["remediation_plan"] and state["remediation_plan"].get("command"):
        command_md = f"```bash\n{state['remediation_plan']['command']}\n```"
    
    # Fill template
    postmortem = POSTMORTEM_TEMPLATE.format(
        incident_id=state["incident_id"],
        incident_type=state["incident_type"],
        severity=state["severity"],
        status="Resolved" if state["approved"] else "Awaiting Approval",
        duration=duration,
        affected_resources=resources_md,
        timeline=timeline_md,
        root_cause=state["root_cause"] or "Under investigation",
        hypotheses=hypotheses_md,
        diagnostics=diagnostics_md,
        remediation_action=state["remediation_plan"]["action_type"] if state["remediation_plan"] else "N/A",
        risk_level=state["remediation_plan"]["risk_level"] if state["remediation_plan"] else "N/A",
        requires_pr="Yes" if state["remediation_plan"] and state["remediation_plan"]["requires_pr"] else "No",
        remediation_description=state["remediation_plan"]["description"] if state["remediation_plan"] else "N/A",
        estimated_impact=state["remediation_plan"]["estimated_impact"] if state["remediation_plan"] else "N/A",
        command=command_md,
        alternatives=alternatives_md,
        preventive_measures=preventive_measures,
        lessons_learned=lessons_learned,
        generated_at=datetime.now(timezone.utc).isoformat()
    )
    
    state["postmortem"] = postmortem
    
    state = add_timeline_entry(
        state,
        agent="postmortem",
        action="generated",
        details="Postmortem documentation created"
    )
    
    return state


def generate_preventive_measures(state: IncidentState) -> str:
    """Generate preventive measures based on incident type and root cause"""
    
    incident_type = state["incident_type"]
    root_cause = state["root_cause"]
    
    measures = []
    
    if "CrashLoopBackOff" in incident_type:
        measures.append("- Add environment variable validation in deployment pipeline")
        measures.append("- Implement config validation tests")
        measures.append("- Set up monitoring alerts for missing dependencies")
    
    if "config" in root_cause.lower():
        measures.append("- Enforce config schema validation")
        measures.append("- Add pre-deployment config checks")
    
    if "env" in root_cause.lower() or "environment" in root_cause.lower():
        measures.append("- Document all required environment variables")
        measures.append("- Add startup dependency checks")
    
    measures.append("- Improve observability with structured logging")
    measures.append("- Add health check endpoints")
    
    return "\n".join(measures) if measures else "To be determined"


def generate_lessons_learned(state: IncidentState) -> str:
    """Generate lessons learned section"""
    
    lessons = [
        "- Automated diagnostics reduced MTTR significantly",
        "- Clear root cause identification prevented unnecessary escalation"
    ]
    
    if state["remediation_plan"] and state["remediation_plan"]["requires_pr"]:
        lessons.append("- Configuration changes should be validated in staging first")
    
    lessons.append("- Comprehensive monitoring and alerting enabled quick detection")
    
    return "\n".join(lessons)
